# Generated by Django 6.0.2 on 2026-02-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_show_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='show',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='show',
            name='total_seats',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.show')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='myapp.seat'),
        ),
    ]
