# Generated by Django 6.0.2 on 2026-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_booking_seats_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='total_seats',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
