# Generated by Django 6.0.2 on 2026-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_show_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
