# Generated by Django 6.0.2 on 2026-03-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_show_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='available_seats',
        ),
    ]
